request_cpus = 16
request_gpus = 2
request_memory = 128G
request_disk = 40G
requirements = (CUDADeviceName == "NVIDIA A100-SXM4-80GB")
ARCH =
environment = "ARCH=$(ARCH)"
log_root = /fast/pmayilvahanan/condor_logs/widen/fw_mgpu_$(ARCH)_$(ClusterId)
error = $(log_root).err
output = $(log_root).out
log = $(log_root).log
MaxTime = 1800
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))
periodic_release = (JobStatus =?= 5) && (HoldReasonCode =?= 34) && (NumJobStarts < 10)
executable = /lustre/fast/fast/pmayilvahanan/Interplay-LM-Reasoning/scripts/widen_line/fineweb_smoke_mgpu.sh
getenv = True
queue 1
