executable = /usr/bin/apptainer

### CmdLine = bash /home/ubuntu/projects/btraja-internship/external_repo/hands_only/train/mgpt_train_job.sh /home/ubuntu/projects/btraja-internship/external_repo/llm/MotionGPT train.py --cfg /home/bthambiraja/projects/btraja-internship/external_repo/hands_only/_config/baselines/mgpt_mdm_00_train/mgptmdm_00_debug.yaml

CmdLine = /home/bthambiraja/projects/btraja-internship/external_repo/hands_only/train/mgpt_train_job.sh /home/bthambiraja/projects/btraja-internship/external_repo/hands_only/llm/MotionGPT train.py /home/bthambiraja/projects/btraja-internship/external_repo/hands_only/_config/baselines/mgpt_mdm_00_train/mgptmdm_01_condor_test.yaml
arguments = exec --no-home --contain --writable-tmpfs --nv --bind /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu --bind /usr/lib64:/usr/lib64 --bind /home/bthambiraja/projects/btraja-internship/external_repo:/home/bthambiraja/projects/btraja-internship/external_repo --bind /is/cluster/fast/bthambiraja/projects/btraja-internship/assets:/home/bthambiraja/projects/btraja-internship/assets --bind /is/cluster/fast/bthambiraja/projects/datasets:/home/bthambiraja/projects/datasets --bind /is/cluster/fast/bthambiraja/projects/btraja-internship/dump:/home/bthambiraja/projects/btraja-internship/dump --bind /is/cluster/fast/bthambiraja/tmp/:/tmp hoigpt_docker_gl_v4_latest.sif /bin/bash $(CmdLine)

# LOGS
error  = /fast/bthambiraja/projects/motion_root/logs_condor/$(ClusterId).$(ProcId).err
output = /fast/bthambiraja/projects/motion_root/logs_condor/$(ClusterId).$(ProcId).out
log    = /fast/bthambiraja/projects/motion_root/logs_condor/$(ClusterId).$(ProcId).log

# CPU / MEMORY
request_memory = 64000
request_cpus = 12
request_disk = 100G

# GPU
request_gpus = 1
# requirements = (TARGET.CUDAGlobalMemoryMb > 23000) &&  (TARGET.CUDAGlobalMemoryMb < 40000)
# requirements = (TARGET.CUDAGlobalMemoryMb > 25000) &&  (TARGET.CUDAGlobalMemoryMb < 40000) && UtsnameNodename =!= "g034"
# requirements = (TARGET.CUDAGlobalMemoryMb > 42000) &&  (TARGET.CUDAGlobalMemoryMb < 86000)


# EXIT SETTINGS
on_exit_hold = (ExitCode =?= 3)
on_exit_hold_reason = "Checkpointed, will resume"
on_exit_hold_subcode = 2
periodic_release = ( (JobStatus =?= 5) && (HoldReasonCode =?= 3) && (HoldReasonSubCode =?= 2) )

# Retry this job 5 times if non-zero exit code
# max_retries = 1

# max running price
+MaxRunningPrice = 5000
#+RunningPriceExceededAction = "restart"
+RunningPriceExceededAction = "kill"

# https://atlas.is.localnet/confluence/display/IT/How+to+limit+the+running+time+of+a+job+in+the+cluster

# add to job to queue
queue